{
 "title": "Qontract Server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "prod-int : appsrep09ue1-prometheus, stage-int : appsres09ue1-prometheus, prod-ext : appsrep11ue1-prometheus, stage-ext : appsres11ue1-prometheus"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(http_request_duration_seconds_count, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability (selected time range)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\",status_code=\"5xx\"}[$__range])) or vector(0) / sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_request_duration_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\",status_code=\"5xx\"}[5m])) or vector(0) /\nsum(rate(http_request_duration_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Path latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "/graphqlsha/#sha latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphqlsha/#sha\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphqlsha/#sha\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphqlsha/#sha\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "/graphql latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphql\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphql\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphql\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "/reload latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/reload\"}[1h])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/reload\"}[1h])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/reload\"}[1h])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "/sha256 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/sha256\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/sha256\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/sha256\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bundle Object Shas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "qontract_server_bundle_object_shas or qontract_server_bundle_cache_object_shas",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container memory usage vs limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}) by (container) /\nsum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}[5m])) by (container)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}[5m])) by (container)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NodeJS heap used/total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(qontract_server_nodejs_heap_space_size_total_bytes)by(space)",
     "legendFormat": "total {{space}}"
    },
    {
     "expr": "sum(qontract_server_nodejs_heap_space_size_used_bytes)by(space)",
     "legendFormat": "used {{space}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(qontract_server_nodejs_gc_duration_seconds_bucket[5m])) by (le,kind))",
     "legendFormat": "p50 {{kind}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(qontract_server_nodejs_gc_duration_seconds_bucket[5m])) by (le,kind))",
     "legendFormat": "p90 {{kind}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(qontract_server_nodejs_gc_duration_seconds_bucket[5m])) by (le,kind))",
     "legendFormat": "p99 {{kind}}"
    }
   ]
  },
  {
   "title": "NodeJS eventloop lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "qontract_server_nodejs_eventloop_lag_seconds",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}