- name: VaultAuditOptions
  version: '1'
  isInterface: true
  interfaceResolve:
    strategy: fieldMap
    field: _type
    fieldMap:
      file: VaultAuditOptionsFile
  fields:
  - { name: _type, type: string, isRequired: true }

- name: VaultAuditOptionsFile
  version: '1'
  interface: VaultAuditOptions
  fields:
  - { name: _type, type: string, isRequired: true }
  - { name: file_path, type: string, isRequired: true }
  - { name: log_raw, type: string, isRequired: true }
  - { name: hmac_accessor, type: string, isRequired: true }
  - { name: mode, type: string, isRequired: true }
  - { name: format, type: string, isRequired: true }
  - { name: prefix, type: string, isRequired: true }

- name: VaultAudit
  version: '1'
  fields:
  - { name: _path, type: string, isRequired: true }
  - { name: type, type: string, isRequired: true }
  - { name: description, type: string, isRequired: true }
  - { name: options, type: VaultAuditOptions, isInterface: true, isRequired: true }

- name: VaultAuthConfig
  version: '1'
  isInterface: true
  interfaceResolve:
    strategy: fieldMap
    field: _type
    fieldMap:
      github: VaultAuthConfigGithub
  fields:
  - { name: _type, type: string, isRequired: true }

- name: VaultAuthConfigGithub
  version: '1'
  interface: VaultAuthConfig
  fields:
  - { name: _type, type: string, isRequired: true }
  - { name: organization, type: string, isRequired: true }
  - { name: base_url, type: string, isRequired: true }
  - { name: max_ttl, type: string, isRequired: true }
  - { name: ttl, type: string, isRequired: true }

- name: VaultAuthSettings
  version: '1'
  fields:
  - { name: config, type: VaultAuthConfig, isInterface: true, isRequired: true }

- name: VaultSecretEngineOptions
  version: '1'
  isInterface: true
  interfaceResolve:
    strategy: fieldMap
    field: _type
    fieldMap:
      kv: VaultSecretEngineOptionsKV
  fields:
  - { name: _type, type: string, isRequired: true }

- name: VaultSecretEngineOptionsKV
  version: '1'
  interface: VaultSecretEngineOptions
  fields:
  - { name: _type, type: string, isRequired: true }
  - { name: version, type: string, isRequired: true }

- name: VaultSecretEngine
  version: '1'
  fields:
  - { name: _path, type: string, isRequired: true }
  - { name: type, type: string, isRequired: true }
  - { name: description, type: string, isRequired: true}
  - { name: options, type: VaultSecretEngineOptions, isInterface: true, isRequired: true }

- name: VaultRoleOptions
  version: '1'
  isInterface: true
  interfaceResolve:
    strategy: fieldMap
    field: _type
    fieldMap:
      approle: VaultApproleOptions
  fields:
  - { name: _type, type: string, isRequired: true }

- name: VaultApproleOptions
  version: '1'
  interface: VaultRoleOptions
  fields:
  - { name: _type, type: string, isRequired: true }
  - { name: bind_secret_id, type: string, isRequired: true }
  - { name: local_secret_ids, type: string, isRequired: true }
  - { name: period, type: string, isRequired: true }
  - { name: secret_id_num_uses, type: string, isRequired: true }
  - { name: secret_id_ttl, type: string, isRequired: true }
  - { name: token_max_ttl, type: string, isRequired: true }
  - { name: token_num_uses, type: string, isRequired: true }
  - { name: token_ttl, type: string, isRequired: true }
  - { name: token_type, type: string, isRequired: true }
  - { name: bound_cidr_list, type: string, isList: true, isRequired: true }
  - { name: policies, type: string, isList: true, isRequired: true }
  - { name: secret_id_bound_cidrs, type: string, isList: true, isRequired: true }
  - { name: token_bound_cidrs, type: string, isList: true, isRequired: true }

- name: VaultRole
  version: '1'
  fields:
  - { name: name, type: string, isRequired: true }
  - { name: type, type: string, isRequired: true }
  - { name: mount, type: string, isRequired: true }
  - { name: options, type: VaultRoleOptions, isInterface: true, isRequired: true }

- name: VaultPolicy
  version: '1'
  fields:
  - { name: name, type: string, isRequired: true }
  - { name: rules, type: string, isRequired: true }

- name: Resource
  version: '1'
  fields:
  - { name: path, type: string, isRequired: true}
  - { name: content, type: string, isRequired: true}
  - { name: sha256sum, type: string, isRequired: true}

- name: VaultSecret
  version: '1'
  fields:
  - { name: path, type: string, isRequired: true }
  - { name: field, type: string, isRequired: true }
  - { name: format, type: string }

- name: QuayOrg
  version: '1'
  fields:
  - { name: schema, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: labels, type: json }
  - { name: name, type: string, isRequired: true }
  - { name: description, type: string, isRequired: true }
  - { name: managedTeams, type: string, isList: true, isRequired: true }
  - { name: automationToken, type: VaultSecret }

- name: Cluster
  version: '1'
  fields:
  - { name: schema, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: labels, type: json }
  - { name: name, type: string, isRequired: true }
  - { name: description, type: string, isRequired: true }
  - { name: serverUrl, type: string, isRequired: true }
  - { name: automationToken, type: VaultSecret }

- name: NamespaceOpenshiftResource
  version: '1'
  isInterface: true
  interfaceResolve:
    strategy: fieldMap
    field: provider
    fieldMap:
      resource: NamespaceOpenshiftResourceResource
      vault-secret: NamespaceOpenshiftResourceVaultSecret
      route: NamespaceOpenshiftResourceRoute
  fields:
  - { name: provider, type: string, isRequired: true }

- name: NamespaceOpenshiftResourceResource
  version: '1'
  interface: NamespaceOpenshiftResource
  fields:
  - { name: provider, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }

- name: NamespaceOpenshiftResourceVaultSecret
  version: '1'
  interface: NamespaceOpenshiftResource
  fields:
  - { name: provider, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: version, type: int, isRequired: true }
  - { name: name, type: string }
  - { name: labels, type: json }
  - { name: annotations, type: json }

- name: NamespaceOpenshiftResourceRoute
  version: '1'
  interface: NamespaceOpenshiftResource
  fields:
  - { name: provider, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: vault_tls_secret_path, type: string }
  - { name: vault_tls_secret_version, type: int }

- name: Namespace
  version: '1'
  fields:
  - { name: schema, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: labels, type: json }
  - { name: name, type: string, isRequired: true }
  - { name: description, type: string, isRequired: true }
  - { name: cluster, type: Cluster, isRequired: true }
  - { name: managedRoles, type: string, isList: true}
  - { name: managedResourceTypes, type: string, isList: true}
  - { name: openshiftResources, type: NamespaceOpenshiftResource, isList: true, isInterface: true}

- name: AppServiceOwner
  version: '1'
  fields:
  - { name: name, type: string, isRequired: true }
  - { name: email, type: string, isRequired: true }

- name: AppPerformanceParameters
  version: '1'
  fields:
  - { name: SLO, type: float, isRequired: true }
  - { name: SLA, type: float }
  - { name: statusPage, type: string }

- name: AppDependencies
  version: '1'
  fields:
  - { name: name, type: string, isRequired: true }
  - { name: statefulness, type: string, isRequired: true }
  - { name: opsModel, type: string, isRequired: true }
  - { name: statusPage, type: string }
  - { name: SLA, type: float, isRequired: true }
  - { name: dependencyFailureImpact, type: string, isRequired: true }

- name: AppQuayReposItems
  version: '1'
  fields:
  - { name: name, type: string, isRequired: true }
  - { name: description, type: string, isRequired: true }
  - { name: public, type: boolean, isRequired: true }

- name: AppQuayRepos
  version: '1'
  fields:
  - { name: org, type: QuayOrg, isRequired: true }
  - { name: items, type: AppQuayReposItems, isRequired: true, isList: true }

- name: AppEscalationsEscalation
  version: '1'
  fields:
  - { name: labels, type: json }
  - { name: slackRecipients, type: string, isList: true }
  - { name: emailRecipients, type: string, isList: true }
  - { name: mattermostRecipients, type: string, isList: true }

- name: AppEscalations
  version: '1'
  fields:
  - { name: default, type: AppEscalationsEscalation }
  - { name: warning, type: AppEscalationsEscalation }
  - { name: critical, type: AppEscalationsEscalation }

- name: App
  version: '1'
  fields:
  - { name: schema, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: labels, type: json }
  - { name: title, type: string, isRequired: true }
  - { name: serviceDocs, type: string, isList: true }
  - { name: serviceOwner, type: AppServiceOwner, isRequired: true }
  - { name: dependencies, type: AppDependencies, isList: true }
  - { name: quayRepos, type: AppQuayRepos, isList: true }
  - { name: escalations, type: AppEscalations, isList: true }

- name: Permission
  version: '1'
  isInterface: true
  interfaceResolve:
    strategy: fieldMap
    field: service
    fieldMap:
      aws-analytics: PermissionAWSAnalytics
      github-org: PermissionGithubOrg
      github-org-team: PermissionGithubOrgTeam
      openshift-rolebinding: PermissionOpenshiftRolebinding
      quay-membership: PermissionQuayOrgTeam
  fields:
  - { name: service, type: string, isRequired: true }

- name: PermissionAWSAnalytics
  version: '1'
  interface: Permission
  fields:
  - { name: service, type: string, isRequired: true }

- name: PermissionGithubOrg
  version: '1'
  interface: Permission
  fields:
  - { name: service, type: string, isRequired: true }
  - { name: org, type: string, isRequired: true }

- name: PermissionGithubOrgTeam
  version: '1'
  interface: Permission
  fields:
  - { name: service, type: string, isRequired: true }
  - { name: org, type: string, isRequired: true }
  - { name: team, type: string, isRequired: true }

- name: VaultPolicyMapping
  version: '1'
  fields:
  - { name: github_team, type: PermissionGithubOrgTeam, isRequired: true }
  - { name: policies, type: VaultPolicy, isList: true, isRequired: true }

- name: VaultAuth
  version: '1'
  fields:
  - { name: _path, type: string, isRequired: true }
  - { name: type, type: string, isRequired: true }
  - { name: description, type: string, isRequired: true }
  - { name: settings, type: VaultAuthSettings }
  - { name: policy_mappings, type: VaultPolicyMapping, isList: true }

- name: PermissionOpenshiftRolebinding
  version: '1'
  interface: Permission
  fields:
  - { name: service, type: string, isRequired: true }
  - { name: cluster, type: string, isRequired: true }
  - { name: namespace, type: string, isRequired: true }
  - { name: role, type: string, isRequired: true }

- name: PermissionQuayOrgTeam
  version: '1'
  interface: Permission
  fields:
  - { name: service, type: string, isRequired: true }
  - { name: org, type: string, isRequired: true }
  - { name: team, type: string, isRequired: true }

- name: User
  version: '1'
  fields:
  - { name: schema, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: labels, type: json }
  - { name: name, type: string, isRequired: true }
  - { name: redhat_username, type: string, isRequired: true }
  - { name: github_username, type: string, isRequired: true }
  - { name: quay_username, type: string }

- name: Bot
  version: '1'
  fields:
  - { name: schema, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: labels, type: json }
  - { name: name, type: string, isRequired: true }
  - { name: github_username, type: string }
  - { name: quay_username, type: string }
  - { name: owner, type: User }

- name: Role
  version: '1'
  datafile: /access/role-1.yml
  fields:
  - { name: schema, type: string, isRequired: true }
  - { name: path, type: string, isRequired: true }
  - { name: labels, type: json }
  - { name: name, type: string, isRequired: true }
  - { name: permissions, type: Permission, isList: true, isInterface: true }
  - name: users
    type: User
    isList: true
    synthetic:
      schema: /access/user-1.yml
      subAttr: roles
  - name: bots
    type: Bot
    isList: true
    synthetic:
      schema: /access/bot-1.yml
      subAttr: roles

- name: Query
  fields:
  - { name: users, type: User, isList: true, datafileSchema: /access/user-1.yml }
  - { name: bots, type: Bot, isList: true, datafileSchema: /access/bot-1.yml }
  - { name: roles, type: Role, isList: true, datafileSchema: /access/role-1.yml }
  - { name: clusters, type: Cluster, isList: true, datafileSchema: /openshift/cluster-1.yml }
  - { name: namespaces, type: Namespace, isList: true, datafileSchema: /openshift/namespace-1.yml }
  - { name: quay_orgs, type: QuayOrg, isList: true, datafileSchema: /dependencies/quay-org-1.yml }
  - { name: apps, type: App, isList: true, datafileSchema: /app-sre/app-1.yml }
  - { name: resources, type: Resource, isResource: true, isRequired: true, isList: true }
  - { name: vault_audit_backends, type: VaultAudit, isList: true, datafileSchema: /vault-config/audit-1.yml }
  - { name: vault_auth_backends, type: VaultAuth, isList: true, datafileSchema: /vault-config/auth-1.yml }
  - { name: vault_secret_engines, type: VaultSecretEngine, isList: true, datafileSchema: /vault-config/secret-engine-1.yml }
  - { name: vault_roles, type: VaultRole, isList: true, datafileSchema: /vault-config/role-1.yml }
  - { name: vault_policies, type: VaultPolicy, isList: true, datafileSchema: /vault-config/policy-1.yml }
