---
apiVersion: v1
kind: Template
metadata:
  name: app-interface
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: app-interface
    name: app-interface
  spec:
    replicas: 1
    selector:
      app: app-interface
      deploymentconfig: app-interface
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: app-interface
          deploymentconfig: app-interface
      spec:
        containers:
        - image: ${IMAGE_GATE}:${IMAGE_GATE_TAG}
          imagePullPolicy: Always
          name: app-interface-nginx-gate
          env:
            - name: HTPASSWD
              valueFrom:
                secretKeyRef:
                    key: htpasswd
                    name: app-interface
            - name: FORWARD_HOST
              valueFrom:
                configMapKeyRef:
                  key: forward_host
                  name: app-interface
          ports:
          - name: nginx-gate-port
            containerPort: 8080
          resources:
            limits:
              memory: ${GATE_MEMORY_LIMIT}
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: app-interface
          env:
            - name: LOAD_METHOD
              valueFrom:
                configMapKeyRef:
                  key: load_method
                  name: app-interface
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                    key: aws.access.key.id
                    name: app-interface
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                    key: aws.region
                    name: app-interface
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                    key: aws.s3.bucket
                    name: app-interface
            - name: AWS_S3_KEY
              valueFrom:
                secretKeyRef:
                    key: aws.s3.key
                    name: app-interface
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                    key: aws.secret.access.key
                    name: app-interface
          ports:
          - name: app-interface
            containerPort: 4000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: app-interface-nginx-gate
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      deploymentconfig: app-interface
- apiVersion: v1
  kind: Service
  metadata:
    name: app-interface
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 4000
    selector:
      deploymentconfig: app-interface
parameters:
- name: IMAGE
  value: quay.io/app-sre/qontract-server
  displayName: App interface image
  description: App interface docker image. Defaults to quay.io/app-sre/app-interface
- name: IMAGE_TAG
  value: latest
  displayName: App interface version
  description: App interface version which defaults to latest
- name: MEMORY_LIMIT
  value: 512Mi
  displayName: Memory Limit
  description: Maximum amount of memory the container can use. Defaults 512Mi
- name: IMAGE_GATE
  value: quay.io/app-sre/nginx-gate
- name: IMAGE_GATE_TAG
  value: latest
  displayName: App interface nginx gate version
  description: App interface nginx gate version which defaults to latest
- name: GATE_MEMORY_LIMIT
  value: 256Mi
